### ISSUE TITLE
Its me, or the css files in the repo are the exact same than the original twitter bootstrap css ?

### ISSUE THREAD

**Issue by rbecheras** [littlesparkvt/Flatstrap-for-Bootstrap-3#10]
If y include de CSS and CSS theme in my HTML, I see zero differences..

So I looked this file https://github.com/littlesparkvt/Flatstrap-for-Bootstrap-3/blob/master/dist/css/bootstrap-theme.css

And I see gradients, comments talk about twtbootstrap repo, not about the /littlesparkvt/Flatstrap-for-Bootstrap-3/ one .... So, what is wrong ?

**Comment by zeroxme** [comment]
this repo is not maintained anymore please go to https://github.com/littlesparkvt/Flatstrap
