### ISSUE TITLE
add SCSS support

### ISSUE THREAD

**Issue by zeroxme** [littlesparkvt/Flatstrap-for-Bootstrap-3#3]
[bi-app-sass](https://github.com/anasnakawa/bi-app-sass) should be supported just like what we did with LESS

**Comment by quanghoc** [comment]
+1

2.3.2 had SCSS here https://github.com/littlesparkvt/flatstrap/tree/master/assets/scss but this version does not. I REALLY REALLY need it guys. Thanks for the great work!

**Comment by zeroxme** [comment]
I'm not sure if I got u right or not but do u want the support of bi-app-sass here in BS3 ... right ?

**Comment by zeroxme** [comment]
Done
