### ISSUE TITLE
bower support

### ISSUE THREAD

**Issue by luisrudge** [littlesparkvt/Flatstrap-for-Bootstrap-3#5]
I don't see this on bower yet :(
http://sindresorhus.com/bower-components/#!/search/flatstrap

**Comment by zeroxme** [comment]
sure thing dude ... let me update the version of bootstrap and i'll submit it on bower

**Comment by zeroxme** [comment]
now you can install via bower by typing `bower install flatstrap3`

**Comment by luisrudge** [comment]
:heart:
