### ISSUE TITLE
well not working properly

### ISSUE THREAD

**Issue by srivathsaharish** [littlesparkvt/Flatstrap-for-Bootstrap-3#6]
I was trying flatstrap with bootstrap 3. However I am not able to get around this issue that the contents of the well are exceeding its border limits. I tried the same with just bootstrap 3 and not with flatstrap, it worked properly.

**Comment by zeroxme** [comment]
i'm not really sure but if you run the docs locally you'll notice that it's fine!

**Comment by srivathsaharish** [comment]
Do you mean having the css, fonts and js file locally by "run the docs locally"? If so, I am already having them locally, do you have any place where I can see it working? Thanks

**Comment by zeroxme** [comment]
the instructions are here https://github.com/littlesparkvt/Flatstrap-for-Bootstrap-3#running-documentation-locally ... plus you can read the original bootstrap documentation here http://getbootstrap.com/components/#wells
